name: Build OpenSmallalk VM

on:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.arch }}
    runs-on: ${{ matrix.dist }}
    
    strategy:
      matrix:
        include:
          - dist: ubuntu-latest
            arch: linux64x64
            bits: 64
          - dist: ubuntu-latest
            arch: linux32x86
            bits: 32
    
    env:
      ARCH: ${{ matrix.arch }}
      FLAVOR: squeak.cog.spur
      ARTIFACT_NAME: ${{ matrix.arch }}

    steps:
      - name: Checkout repository OpenSmalltalk/opensmalltalk-vm
        uses: actions/checkout@v2
        with:
          repository: 'OpenSmalltalk/opensmalltalk-vm'
          ref: '9f1b4644e7396e473bd9bb4cf67f8a9d5a4e11d6'

      - name: Install dependencies
        run: ./scripts/ci/travis_install.sh
      
      - name: Run source tree version substitutions
        run: ./scripts/updateSCCSVersions
      
      - name: Run "make config" in platforms/unix/config ...
        working-directory: ./platforms/unix/config/
        run: make configure
      
      - name: Make VM
        working-directory: ./build.${{ env.ARCH }}/${{ env.FLAVOR }}/build/
        run: echo "n" | ./mvm
      
      - name: Pack VM
        working-directory: ./products/
        run: tar --create --gzip --file="${{ env.ARTIFACT_NAME }}.tar.gz" *
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./products/${{ env.ARTIFACT_NAME }}.tar.gz
      
      - name: Setup hpi-swa/smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: Squeak${{ matrix.bits }}-trunk
      
      - name: Run tests
        continue-on-error: true
        run: smalltalkci -s Squeak${{ matrix.bits }}-trunk --vm ./products/sqcogspur${{ matrix.bits }}linuxht/bin/squeak ./tests/smalltalk.ston
