name: Build OpenSmallalk VM

on:
  workflow_dispatch:

env:
  FLAVOR: squeak.cog.spur
  PRODUCT_PATH: ${{ env.GITHUB_WORKSPACE }}/product/

jobs:
  linux-build:
    name: ${{ matrix.arch }}
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: linux64x64
            bits: 64
    
    env:
      ARCH: ${{ matrix.arch }}
      ARTIFACT_NAME: ${{ matrix.arch }}
    
    steps:
      - name: Checkout repository OpenSmalltalk/opensmalltalk-vm
        uses: actions/checkout@v2
        with:
          repository: 'OpenSmalltalk/opensmalltalk-vm'
          ref: '9f1b4644e7396e473bd9bb4cf67f8a9d5a4e11d6'
      
      - name: Install dependencies
        run: ./scripts/ci/travis_install.sh
      
      - name: Run source tree version substitutions
        run: ./scripts/updateSCCSVersions
      
      - name: Run 'make config' in platforms/unix/config ...
        working-directory: ./platforms/unix/config/
        run: make configure
      
      - name: Make VM
        working-directory: ./build.${{ env.ARCH }}/${{ env.FLAVOR }}/build/
        run: echo "n" | ./mvm
      
      - name: Move VM
        working-directory: ./products/sqcogspur${{ matrix.bits }}linuxht
        run: mkdir -p ${{ env.PRODUCT_PATH }} && mv * ${{ env.PRODUCT_PATH }}
      
      - name: Pack VM
        working-directory: ${{ env.PRODUCT_PATH }}
        run: tar --create --gzip --file="${{ env.ARTIFACT_NAME }}.tar.gz" *
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PRODUCT_PATH}}/${{ env.ARTIFACT_NAME }}.tar.gz

  windows-build:
    name: ${{ matrix.arch }}
    runs-on: windows-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: win64x64
            bits: 64
            mingw_arch: x86_64
            cyg_root: C:\cygwin64
    
    env:
      ARCH: ${{ matrix.arch }}
      ARTIFACT_NAME: ${{ matrix.arch }}
    
    defaults:
      run:
        shell: bash
    
    steps:
      - name: Checkout repository OpenSmalltalk/opensmalltalk-vm
        uses: actions/checkout@v2
        with:
          repository: 'OpenSmalltalk/opensmalltalk-vm'
          ref: '9f1b4644e7396e473bd9bb4cf67f8a9d5a4e11d6'
      
      - name: Reuse Cygwin from Cache
        id: cygwin-cache
        uses: actions/cache@v2
        with:
          path: ${{ matrix.cyg_root }}
          key: cygwin-${{ matrix.arch }}-1
        
      - name: Install Cygwin
        if: ${{ !steps.cygwin-cache.outputs.cache-hit }}
        run: |
          curl -fsSL --retry 4 -m 600 -o "setup-x86.exe" "http://cygwin.com/setup-x86.exe"
          curl -fsSL --retry 4 -m 600 -o "setup-x86_64.exe" "http://cygwin.com/setup-x86_64.exe"
      
      - name: Install dependencies
        if: ${{ !steps.cygwin-cache.outputs.cache-hit }}
        shell: cmd
        run: call scripts/installCygwin.bat ${{ matrix.mingw_arch }} ${{ matrix.cyg_root }}
      
      - name: Add Cygwin to PATH
        run: echo "${{ matrix.cyg_root }}\bin" >> $GITHUB_PATH

      - name: Run source tree version substitutions
        run: ./scripts/updateSCCSVersions
      
      - name: Make VM
        working-directory: ./build.${{ env.ARCH }}/${{ env.FLAVOR }}/
        run: ./mvm -f
      
      - name: Move VM
        working-directory: ./build.${{ env.ARCH }}/${{ env.FLAVOR }}/build/vm
        run: mkdir -p ${{ env.PRODUCT_PATH }} && mv *.dll *.exe* ${{ env.PRODUCT_PATH }}
      
      - name: Pack VM
        working-directory: ${{ env.PRODUCT_PATH }}
        run: tar --create --gzip --file="${{ env.ARTIFACT_NAME }}.tar.gz" *
      
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.PRODUCT_PATH}}/${{ env.ARTIFACT_NAME }}.tar.gz
